export class confirmationclass{
  constructor(
    public order_id?:number,
    public order_amount?:number,
    public order_qty?:number,
    public fk_product_id?:number,
    public fk_email_id?:string,
    public fk_main_order_id?:number,
    public mainorder_id?:number,
    public mainorder_amount?:number,
    public mainorder_date?:Date,
    public user_email_id?:string,
    public user_name?:string,
    public user_mobile_no?:number,
    public user_gender?:string,
    public user_dob?:Date,
    public user_password?:string,
    public user_address?:string,
    public type?:string,
    public payment_id?:number,
    public payment_date?:Date,
    public amount?:number,
    public payment_mode?:string,
    public fk_mainorder_id?:string,
    public fk_brand_id?:number,
    public product_discription?:string,
    public product_id?:number,
    public product_image?:string,
    public product_name?:string,
    public product_price?:number,
    public product_qty?:number,
    ){}
}

